### ISSUE TITLE
Download failing (folder permissions maybe?)

### ISSUE THREAD

**Issue by elihubogan** [wp-kitten/envato-update-plugins#1]
Hi there, this is an inspired idea, but implementation for me hit a little speedbump when attempting to update Envato plugins. I get the following error (using the Woocommerce Availability Notifications plugin for example):

An error occurred while updating WooCommerce Availability Notifications: Download failed. Could not open handle for fopen() to /tmp/woocommerce-availability-notifications.zip[/\* redacted AWS credentials */]response-content-dispositionattachment%3B-filename%3Dcodecanyon-8422290-woocommerce-availability-notifications-wordpress-plugin.tmp

Would love to help troubleshoot. Example plugin is here:

http://codecanyon.net/item/woocommerce-availability-notifications/8422290

**Comment by wp-kitten** [comment]
Hello, @elihubogan 

Thank you for letting me know. I didn't buy that plugin from TF, so I won't be able to test with it, but I will try with an other plugin and see if this error is related to your plugin only or is affecting others too.

Thanks again!

Costin

**Comment by wp-kitten** [comment]
Hello,

After some debugging, it doesn't seem to be a folder permission. WordPress doesn't handle the envato's download url to Amazon properly and returns a temp directory name looking like this: 

```
C:\\Windows\\TEMP/js_composer.zipAWSAccessKeyIdDKIAeYG54OGJ6X7t3M6QExpires1442857531SignatureMGc5nhDZv2t%2FpncEh5spBGH7lz0%3Dresponse-content-dispositionattachment%3B-filename%3Dcodecanyon-242431-visual-composer-page-builder-for-wordpress-wordpress-plugin.tmp
```

In which a zip archive with the same name is going to be created, that causing a very long path to the zip file.

ref: https://msdn.microsoft.com/en-us/library/aa365247.aspx#file_and_directory_names

This needs further investigation...

**Comment by wp-kitten** [comment]
It's been a while since my last reply, but I couldn't replicate this issue anymore.
