### ISSUE TITLE
Is this plugin working?

### ISSUE THREAD

**Issue by dejanmarkovic** [wp-kitten/envato-update-plugins#2]
I have tried it on 2 live sites with Ninja Popups and Revolution Slider and it doesn't work. Meaning my installed versions on those sites have lesser numbers than the current versions on Developers pages and I don't see notifications on plugin manager page.

Thanks.

**Comment by wp-kitten** [comment]
Hello, @dejanmarkovic 

I'm really sorry for the late reply, I totally missed your post :(

How about other plugins? Is the same issue present?

Until I hear back from you I will do some more tests and see if I can replicate the problem.

In the meantime, was there any error generated in the error log?

Regards,
Costin

**Comment by davidfavor** [comment]
This plugins doesn't work appears abandoned by the developer.

Use at your own peril.

**Comment by wp-kitten** [comment]
Hi guys!

I'm truly sorry but I have been swamped with work and didn't have time to look over the plugin. I will run some tests on it in the next couple of days and fix any problems I can find.

@davidfavor It would really help if you'd provide more information about what's not working, it would make the problem solving much easier :)

Regards,
Costin

**Comment by wp-kitten** [comment]
I have pushed a new update. From what I could see, all is working properly.
